### ISSUE TITLE
[Bug] Sample code does not work out of the box

### ISSUE THREAD

**Issue by fugu-chop** [temporalio/money-transfer-project-template-go#38]
### What are you really trying to do?

Trying to run the code as described in the `README.md`.

### Describe the bug

The client in `start/main.go` cannot establish a connection to the local development Temporal server. 

I have not modified any client code and am using all the default options for `client.Options` - i.e. just running 
```go
c, err := client.Dial(client.Options{})
```

I stand up a local development server using `temporal server start-dev --db-filename your_temporal.db --ui-port 8080 ` (installed via `brew`, but I did try using Docker with the same result). 

When running `go run start/main.go`, I get the following error.
```
2025/10/18 14:36:37 INFO  No logger configured for temporal client. Created default one.
2025/10/18 14:36:42 Unable to create Temporal client: failed reaching server: context deadline exceeded
exit status 1
```

**The issue appears to be triggered by the dependency updates** in `5dcebbb5625f67ddb56adbe2787c39e751bd2f40` [commit](https://github.com/temporalio/money-transfer-project-template-go/commit/5dcebbb5625f67ddb56adbe2787c39e751bd2f40) - I am able to checkout previous commits and run the starter code.

### Minimal Reproduction

1. Pull down repo.
2. Stand up any local development Temporal server
3. Run `go run start/main.go`
4. Get the above error.

### Environment/Versions

- Hardware: Apple M4
- OS: macOS Sequoia 15.6.1 
- Go version: go1.24.7 darwin/arm64
- Go SDK version: go.temporal.io/sdk v1.36.0

### Additional context

I suspect it's something to do with the version of `go.temporal.io/sdk` past `v1.17.0`.

**Comment by tomwheeler** [comment]
@fugu-chop Thank you for reporting this, and I sincerely apologize for taking so long to respond. I have a similar setup to yours (M2 MacBook Pro and Go 1.24.7), but could not reproduce the problem. The emoji from @jasonligg suggests that it's not just you, though.

I just pushed [a commit](https://github.com/temporalio/money-transfer-project-template-go/commit/3410a88e49d86b1e8ab2f3005576b02c731e0eca) that updates to the 1.37.0 SDK and related dependencies. I'd appreciate if you could try with the latest code and let me know whether the problem remains.

**Comment by fugu-chop** [comment]
Hi @tomwheeler, pulled down from `main` and I'm still getting the context deadline exceeded issue. It also now seems to happen to me for the `edu-101` and `edu-102` courses since the SDK was bumped to `v1.37.0`. Previously they were fine (I think `main` had an older version of the Go SDK).

For further context, I am able to successfully get everything working in the `edu-interacting-with-workflows-go-code` repo, which uses `go.temporal.io/sdk v1.26.1`.

**Comment by tomwheeler** [comment]
Hi @fugu-chop, thanks for the update. I have tried unsuccessfully to reproduce this issue on three different machines, two running macOS and another running Linux. 

However, I did some research and found what I think is a relevant (now-closed) [issue](https://github.com/temporalio/sdk-go/issues/1834) filed against the Go SDK repo. The synopsis is that another user reported getting "Context deadline exceeded" errors with the Go SDK and one of our engineers helped to find the root cause. The underlying gRPC library changed how it does hostname resolution (as [explained in an issue](https://github.com/grpc/grpc-go/issues/7429#issuecomment-2904414141) on that project's repo).

To see if that's what is causing the problem for you, would you mind modifying these two lines of code:

- https://github.com/temporalio/money-transfer-project-template-go/blob/main/worker/main.go#L15
- https://github.com/temporalio/money-transfer-project-template-go/blob/main/start/main.go#L15

in your local copy, changing it from this:

```go
	c, err := client.Dial(client.Options{})
```

to this:

```go
	c, err := client.Dial(client.Options{
		HostPort: "passthrough:///localhost:7233",
	})
```

Please let me know if that fixes it.

**Comment by fugu-chop** [comment]
Thanks for your help @tomwheeler, that does solve it. 

Looks like it might be that DNS resolver issue in `grpc-go` (I assume this is used inside the Go SDK), since this works for me as well:
```go
	c, err := client.Dial(client.Options{
		HostPort: "127.0.0.1:7233",
	})
```
Since the aforementioned issue in the `grpc-go` appears to be fixed with their `v1.75.0` release (latest version of `grpc-go` is now `v1.76.0`), might be worth upgrading to that version (assuming it isn't already)?
